### ISSUE TITLE
Add cooldown to hitting multi-coin blocks

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/mroyale-client#3]
There is currently no cooldown when hitting multi-coin blocks. This behavior is quite jarring on levels (mostly those not from SMB1) that have a small gap between the block and the floor. Adding a cooldown would not only be more faithful to Mario physics but also add some slight balance as you wouldn’t be able to just spam jump to grab a bunch of coins and move on — you’d have to wait, therefore allowing others to catch up or pass you.

**Comment by terminalarch** [comment]
Just asking, how would this work? Not allowing the block to be hit or adding a jumping cooldown?

**Comment by Nightcaat** [comment]
If I did the math correctly, to be faithful to SMB1, there should be an approximately 0.27-second cooldown during which trying to hit the block again will make you bonk your head and not give you a coin.

Multi-coin blocks are also supposed to run on a timer starting from the first hit, but I think just having this cooldown in place is good enough for now.

**Comment by terminalarch** [comment]
Got it, will add for version 4.4
