### ISSUE TITLE
Add an animated favicon

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/mroyale-client#9]
I can take care of this myself when I have time.

As far as I know, only Firefox has native support for animated favicons, so if the user agent reports itself as anything but Firefox, JavaScript should be used to inject fallback icons (in my testing, if you just leave all of the tags in, Firefox will use the fallback icons instead). It would be possible to use JavaScript to cycle between frames on other browsers, but it has some issues and is likely not worth implementing.

In the future, if people find it annoying, perhaps it could be disabled by default and toggled on somewhere? If an SVG is used instead of a GIF, it should also be possible to respect the [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) CSS media query and disable the animation if the browser reports that the reduce motion accessibility feature is enabled.

**Comment by terminalarch** [comment]
I won't lie, this is my first time ever hearing of animated favicons

**Comment by terminalarch** [comment]
9 days later yeah I still don't get the point
